config/routes.rb
Yupp::Application.routes.draw do
  resources :users, :only => [:index, :show, :edit, :update]
   
  resources :ideas do
    get :recent, :on => :collection
    get :popular, :on => :collection 
  end
  
  match 'login' => 'sessions#login'
  match 'logout' => 'sessions#logout'
  match 'auth/:provider/callback' => 'sessions#create'
  match 'search' => 'search#index'

  root :to => 'ideas#popular'
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
  attr_accessible :user_id, :provider, :uid
  validates_presence_of :user_id, :provider, :uid
  validates_uniqueness_of :uid, :scope => :provider
        
  def self.find_or_create_from_hash(hash, user = nil)
    provider = hash['provider']
    uid = hash['uid']
    auth = find_by_provider_and_uid(provider, uid)

    if !auth
      user ||= User.create_from_hash!(hash)
      auth = Authorization.create(:user_id => user.id, :uid => uid, :provider => provider)
    end
    
    auth
  end
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :body, :category, :title

  extend FriendlyId
  friendly_id :title, :use => :slugged
  belongs_to :user

  def can_edit?(user)
    self.user == user
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :display_name, :email, :image, :name, :phone, :slug

  extend FriendlyId
  friendly_id :name, :use => :slugged 
  has_many :authorizations
  has_many :ideas

  def self.create_from_hash!(hash)
    info = hash['info']
    user = create(
      :display_name => info['name'],
      :name => info['nickname'],
      :email => info['email'],
      :phone => info['phone'],
      :image => info['image']
    )
    user
  end
  
  def best_image_url
    image || 'avatar-male.png'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :signed_in?, :is_me?
  layout Proc.new { |c| c.request.xhr? ? false : 'application' }
  
  def current_user
    begin
      @current_user ||= (session[:user_id] && User.find_by_id!(session[:user_id]))
    rescue ActiveRecord::RecordNotFound
      nil
    end
  end

  def current_user=(user)
    @current_user = user
    if user.nil?
      session[:user_id] = nil
    else
      session[:user_id] = user.id
    end
  end
  
  def signed_in?
    !!current_user
  end

  def is_me?(u)
    signed_in? and current_user == u
  end
  
  def require_login
    redirect_to login_path unless signed_in?
  end

  def require_admin_rights
    unless signed_in? && current_user.has_admin_rights?
      redirect_to_404
    end
  end

  def render_not_found
    respond_to do |format|
      format.json { render :nothing => true, :status => 404 }
      format.html { render 'shared/not_found', :status => 404 }
    end
    true
  end

  def render_forbidden
    respond_to do |format|
      format.json { render :nothing => true, :status => 403 }
      format.html { render 'shared/forbidden', :status => 403 }
    end
    true
  end

  def redirect_to_stored
    if return_to = session[:return_to]
      session[:return_to] = nil
      redirect_to return_to
    else
      redirect_to '/'
    end
  end

  def redirect_to_back(default = root_path)
    redirect_to :back
  rescue ActionController::RedirectBackError
    redirect_to default
  end
end

app/controllers/general_controller.rb
class GeneralController < ApplicationController
  def welcome
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
   before_filter :require_login, :only => [:new, :create, :edit, :update, :destroy]
   helper_method :can_edit?

   def can_edit?
     current_user and @idea.can_edit?(current_user)
   end

   def recent
     @ideas = Idea.all
     
     respond_to do |format|
       format.html { render :template => 'ideas/index' }
       format.json { render json: @ideas }
     end
   end

   def popular
     @ideas = Idea.all

     respond_to do |format|
       format.html { render :template => 'ideas/index' }
       format.json { render json: @ideas }
     end
   end

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])

    render_not_found and return unless @idea
    render_forbidden and return unless can_edit?
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    render_not_found and return unless @idea
    render_forbidden and return unless can_edit?

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])

    render_not_found and return unless @idea
    render_forbidden and return unless can_edit?

    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create 
    @auth = Authorization.find_or_create_from_hash(auth_hash, current_user)
    self.current_user = @auth.user
    redirect_to_back(root_path)
  end
  
  def login
  end

  def logout
    self.current_user = nil
    redirect_to_back(root_path)
  end
        
  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/general/welcome.html.erb
<h1>General#welcome</h1>
<p>Find me in app/views/general/welcome.html.erb</p>

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<div class="primary-heading">
  <h1>Editing idea</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<div class="secondary-nav flush">
  <ul>
    <li><%= link_to('Recent', recent_ideas_path, :class => 'btn') %></li>
    <li><%= link_to('Popular', popular_ideas_path, :class => 'btn') %></li>
  </ul>
</div>

<div class="ideas flush">
  <% if @ideas.count > 0 %>
    <% @ideas.each do |idea| %>
      <div class="idea flush">
        <div class="rating">
          <%= image_tag('bulb.jpg') %>
        </div>
        <div class="content">
          <p class="title">
            <%= link_to(idea.title, idea) %>
          </p>
          <div class="body">
            <p class="body-short">
              <%= idea.body.length > 200 ? idea.body[0..200] + '...' : idea.body %>
            </p>
            <p class="body-full" style="display:none;">
              <%= idea.body %>
            </p>
          </div>
        </div>

        <div class="footer">
          <div class="left">
            <%= link_to('12 comments', '#') %>
            <%= link_to('share', '#') %>
          </div>
          <div class="right">
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>There is nothing here</p>
  <% end %> 
</div>

app/views/ideas/new.html.erb
<div class="primary-heading">
  <h1>New idea</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<%- model_class = Idea -%>
<div class="primary-heading">
  <h1><%= @idea.title %></h1>
</div>

<% if can_edit? %>
<div class="form-actions">
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_idea_path(@idea), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              idea_path(@idea),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
<% end %>

<div class="idea-body">
  <p><%= @idea.body %></p>
</div>

<div class="secondary-heading">
  <h1>Comments</h1>
</div>

<h2>Coming soon</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "Yupp" %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render :partial => 'shared/login' %>

  <div id="page">
    <%= render :partial => 'shared/header' %>

    <div id="page-body">
      <div class="container-center">
        <div class="contained">
          <%= content_for?(:content) ? yield(:content) : yield %>
        </div>
      </div>
    </div>

    <%= render :partial => 'shared/footer' %>
  </div>

</body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <div id="footer-inner">
  <ul class="nav">
    <li><%= link_to 'About', '', :class => 'sv-about-button' %></li>
    <li><%= link_to 'Developers', '', :class => 'sv-devs-button' %></li>
    <li><%= link_to 'Feedback', '', :class => 'sv-feedback-button' %></li>
    <li><%= link_to 'Privacy', '', :class => 'sv-privacy-button' %></li>
    <li><%= link_to 'Terms', '', :class => 'sv-terms-button' %></li>
  </ul>
  <div class="copyright">
    Yupp, LLC © 2013
  </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div id="header">
<div class="header-inner">
  <% link_to(content_tag(:span, '', :class => 'logo'), root_path, :class => 'home-link') %>
  <%= link_to('Yupp', root_path, :class => 'logo-txt') %><div class="logo-beta">beta</div>
  <div id="secondary-nav">
    <ul>
      <% if signed_in? %>
        <li>
          <%= link_to('New Idea', new_idea_path, :class => 'link button-invite') %>
        </li>
        <li>
          <%= link_to(image_tag(current_user.best_image_url, :class => 'user-image', :title => current_user.display_name), user_path(current_user)) %>
        </li>
      <% end %>
        <li>
        <% if signed_in? %>
          <%= link_to('Sign Out', logout_path, :class => 'button-logout') %>
        <% else %>
          <%= link_to('Sign In', '#', :class => 'button button-login') %>
        <% end %>
        </li>
    </ul>
  </div>
  <!--<div id="sv-primary-nav">
    <= top_menu_items %>
  </div>-->
  <div id="search-nav">
    <form method="get" action="/search">
      <div class="form-item" style="display: block;">
        <input type="text" placeholder="search" value="" name="q" id="search" class="text">
        <button id="search-submit"></button>
      </div>
    </form>
  </div>
</div>
</div>

app/views/shared/_login.html.erb
<div class="modal two-quarter" id="login-modal">
  <a class="modal-close cancel-modal" href="#"><span class="icon icon-close"></span></a>
  <div class="contained">
    <div class="primary-heading">
      <h1>Sign in</h1>
    </div>
    <div class="flush">
      <div class="module-set">
        <div class="login-buttons">
          <ul>
            <li><%= link_to(image_tag('signin-facebook.png'), '/auth/facebook') %></li>
            <li><%= link_to(image_tag('signin-twitter.png'), '/auth/twitter') %> </li>
          </ul> 
        </div>
      </div>
    </div>
    <div class="flush">
    </div>
  </div>
</div>

<script type="text/javascript">

  $(function() {
    $('#login-modal').dialog({
      autoOpen: false,
      modal: true,
      resizable: false,
      width: 460,
      show: 'explode',
      hide: 'explode',
      dialogClass: 'sv-dialog'
    });
    $(document).on('click', '.button-login', function(e) {
      $('#login-modal').dialog('open');
    });
  });

</script>